FROM node:24-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
EXPOSE 3001
CMD ["sh", "-c", "npm install && rm -rf /app/src/generated/prisma && npx prisma generate && npx prisma migrate deploy && npm run dev"]
